[YouTube ]
enabled = false
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube/"
patches-source = "inotia00/revanced-patches"
integrations-source = "inotia00/revanced-integrations"
rv-brand = "RVX"
build-mode = "module"
included-patches = "'Add splash animation' 'Disable landscape mode' 'Hide animated button background' 'Hide double tap overlay filter' 'Hide player button background' 'Hide voice search button'"
excluded-patches = "'MicroG support' 'Translations'"

[YT-Music]
enabled = true
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube-music/"
patches-source = "inotia00/revanced-patches"
integrations-source = "inotia00/revanced-integrations"
rv-brand = "RVX"
build-mode = "module"
excluded-patches = "'Custom package name' 'Translations'"
